server:
  port: 8091
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeeapp
    username: root
    password: admin12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "test.webapp.employee.model"